[2025-07-09T09:16:30.747+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T09:15:29.896960+00:00 [queued]>
[2025-07-09T09:16:30.757+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T09:15:29.896960+00:00 [queued]>
[2025-07-09T09:16:30.757+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T09:16:30.767+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_customers> on 2025-07-09 09:15:29.896960+00:00
[2025-07-09T09:16:30.771+0000] {standard_task_runner.py:57} INFO - Started process 520 to run task
[2025-07-09T09:16:30.775+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_customers', 'scheduled__2025-07-09T09:15:29.896960+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmpubyam84x']
[2025-07-09T09:16:30.777+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask extract_transform_customers
[2025-07-09T09:16:30.968+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T09:15:29.896960+00:00 [running]> on host fc060bb3c09b
[2025-07-09T09:16:31.007+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T09:15:29.896960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T09:15:29.896960+00:00'
[2025-07-09T09:16:31.008+0000] {ecommerce_etl_dag.py:32} INFO - Bắt đầu extract customers data...
[2025-07-09T09:16:31.012+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:16:31.014+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.dim_customers CASCADE;, parameters: None
[2025-07-09T09:16:31.025+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:16:31.031+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T09:16:31.034+0000] {ecommerce_etl_dag.py:59} INFO - Extracted 5 customers
[2025-07-09T09:16:31.039+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:16:31.042+0000] {ecommerce_etl_dag.py:83} INFO - Loaded 5 customers vào dim_customers
[2025-07-09T09:16:31.043+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T09:16:31.049+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_customers, execution_date=20250709T091529, start_date=20250709T091630, end_date=20250709T091631
[2025-07-09T09:16:31.080+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T09:16:31.243+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
