[2025-07-09T10:30:19.932+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.data_quality_check scheduled__2025-07-09T10:29:15.291024+00:00 [queued]>
[2025-07-09T10:30:19.937+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.data_quality_check scheduled__2025-07-09T10:29:15.291024+00:00 [queued]>
[2025-07-09T10:30:19.938+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T10:30:19.945+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): data_quality_check> on 2025-07-09 10:29:15.291024+00:00
[2025-07-09T10:30:19.948+0000] {standard_task_runner.py:57} INFO - Started process 3278 to run task
[2025-07-09T10:30:19.949+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'data_quality_check', 'scheduled__2025-07-09T10:29:15.291024+00:00', '--job-id', '482', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmpg0j5bc91']
[2025-07-09T10:30:19.951+0000] {standard_task_runner.py:85} INFO - Job 482: Subtask data_quality_check
[2025-07-09T10:30:20.069+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.data_quality_check scheduled__2025-07-09T10:29:15.291024+00:00 [running]> on host fc060bb3c09b
[2025-07-09T10:30:20.111+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T10:29:15.291024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T10:29:15.291024+00:00'
[2025-07-09T10:30:20.111+0000] {sql.py:274} INFO - Executing: 
    DO $$
    DECLARE
        customer_count INTEGER;
        product_count INTEGER;
        sales_count INTEGER;
    BEGIN
        SELECT COUNT(*) INTO customer_count FROM target_data.dim_customers;
        SELECT COUNT(*) INTO product_count FROM target_data.dim_products;
        SELECT COUNT(*) INTO sales_count FROM target_data.fact_sales;
        
        RAISE NOTICE 'Data quality check: % customers, % products, % sales', 
                     customer_count, product_count, sales_count;
                     
        IF customer_count = 0 THEN
            RAISE WARNING 'No customers in dim_customers';
        END IF;
        
        IF product_count = 0 THEN
            RAISE WARNING 'No products in dim_products';
        END IF;
        
        IF sales_count = 0 THEN
            RAISE WARNING 'No sales in fact_sales';
        END IF;
    END $$;
    
[2025-07-09T10:30:20.115+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:30:20.119+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:30:20.121+0000] {sql.py:418} INFO - Running statement: 
    DO $$
    DECLARE
        customer_count INTEGER;
        product_count INTEGER;
        sales_count INTEGER;
    BEGIN
        SELECT COUNT(*) INTO customer_count FROM target_data.dim_customers;
        SELECT COUNT(*) INTO product_count FROM target_data.dim_products;
        SELECT COUNT(*) INTO sales_count FROM target_data.fact_sales;
        
        RAISE NOTICE 'Data quality check: % customers, % products, % sales', 
                     customer_count, product_count, sales_count;
                     
        IF customer_count = 0 THEN
            RAISE WARNING 'No customers in dim_customers';
        END IF;
        
        IF product_count = 0 THEN
            RAISE WARNING 'No products in dim_products';
        END IF;
        
        IF sales_count = 0 THEN
            RAISE WARNING 'No sales in fact_sales';
        END IF;
    END $$;
    , parameters: None
[2025-07-09T10:30:20.130+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=data_quality_check, execution_date=20250709T102915, start_date=20250709T103019, end_date=20250709T103020
[2025-07-09T10:30:20.172+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T10:30:20.181+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
