[2025-07-09T10:23:17.345+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:22:14.875527+00:00 [queued]>
[2025-07-09T10:23:17.350+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:22:14.875527+00:00 [queued]>
[2025-07-09T10:23:17.350+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T10:23:17.358+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_sales> on 2025-07-09 10:22:14.875527+00:00
[2025-07-09T10:23:17.362+0000] {standard_task_runner.py:57} INFO - Started process 2986 to run task
[2025-07-09T10:23:17.364+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_sales', 'scheduled__2025-07-09T10:22:14.875527+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmp7845kxok']
[2025-07-09T10:23:17.365+0000] {standard_task_runner.py:85} INFO - Job 445: Subtask extract_transform_sales
[2025-07-09T10:23:17.394+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:22:14.875527+00:00 [running]> on host fc060bb3c09b
[2025-07-09T10:23:17.569+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T10:22:14.875527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T10:22:14.875527+00:00'
[2025-07-09T10:23:17.569+0000] {ecommerce_etl_dag.py:151} INFO - Bắt đầu extract sales data...
[2025-07-09T10:23:17.574+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:23:17.579+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.fact_sales CASCADE;, parameters: None
[2025-07-09T10:23:17.587+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:23:17.594+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T10:23:17.601+0000] {ecommerce_etl_dag.py:178} INFO - Extracted 978 sales records
[2025-07-09T10:23:17.606+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:23:17.633+0000] {ecommerce_etl_dag.py:197} INFO - Loaded 978 sales records vào fact_sales
[2025-07-09T10:23:17.634+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T10:23:17.641+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_sales, execution_date=20250709T102214, start_date=20250709T102317, end_date=20250709T102317
[2025-07-09T10:23:17.667+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T10:23:17.688+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
